format_version: v1.0
configName: sam_e51_cnano
folderName: sam_e51_cnano
frameworkPath: D:\Projects\git_hub
processor: ATSAME51J20A
projectName: getting_started_sam_e51_cnano
settings:
  PackageFilter: ''
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: dev_packs\arm\CMSIS\5.7.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: dev_packs\Microchip\SAME51_DFP\3.4.98\atdf\ATSAME51J20A.atdf
